// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CriticalService_Connect_FullMethodName         = "/CriticalService/Connect"
	CriticalService_UpdateNodeCount_FullMethodName = "/CriticalService/UpdateNodeCount"
	CriticalService_RequestAccess_FullMethodName   = "/CriticalService/RequestAccess"
)

// CriticalServiceClient is the client API for CriticalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CriticalServiceClient interface {
	Connect(ctx context.Context, in *ConnectionRequest, opts ...grpc.CallOption) (*ConnectionGrant, error)
	UpdateNodeCount(ctx context.Context, in *ConnectionAmount, opts ...grpc.CallOption) (*Empty, error)
	RequestAccess(ctx context.Context, in *AccessRequest, opts ...grpc.CallOption) (*AccessGrant, error)
}

type criticalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCriticalServiceClient(cc grpc.ClientConnInterface) CriticalServiceClient {
	return &criticalServiceClient{cc}
}

func (c *criticalServiceClient) Connect(ctx context.Context, in *ConnectionRequest, opts ...grpc.CallOption) (*ConnectionGrant, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectionGrant)
	err := c.cc.Invoke(ctx, CriticalService_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *criticalServiceClient) UpdateNodeCount(ctx context.Context, in *ConnectionAmount, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CriticalService_UpdateNodeCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *criticalServiceClient) RequestAccess(ctx context.Context, in *AccessRequest, opts ...grpc.CallOption) (*AccessGrant, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessGrant)
	err := c.cc.Invoke(ctx, CriticalService_RequestAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CriticalServiceServer is the server API for CriticalService service.
// All implementations must embed UnimplementedCriticalServiceServer
// for forward compatibility.
type CriticalServiceServer interface {
	Connect(context.Context, *ConnectionRequest) (*ConnectionGrant, error)
	UpdateNodeCount(context.Context, *ConnectionAmount) (*Empty, error)
	RequestAccess(context.Context, *AccessRequest) (*AccessGrant, error)
	mustEmbedUnimplementedCriticalServiceServer()
}

// UnimplementedCriticalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCriticalServiceServer struct{}

func (UnimplementedCriticalServiceServer) Connect(context.Context, *ConnectionRequest) (*ConnectionGrant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedCriticalServiceServer) UpdateNodeCount(context.Context, *ConnectionAmount) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNodeCount not implemented")
}
func (UnimplementedCriticalServiceServer) RequestAccess(context.Context, *AccessRequest) (*AccessGrant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestAccess not implemented")
}
func (UnimplementedCriticalServiceServer) mustEmbedUnimplementedCriticalServiceServer() {}
func (UnimplementedCriticalServiceServer) testEmbeddedByValue()                         {}

// UnsafeCriticalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CriticalServiceServer will
// result in compilation errors.
type UnsafeCriticalServiceServer interface {
	mustEmbedUnimplementedCriticalServiceServer()
}

func RegisterCriticalServiceServer(s grpc.ServiceRegistrar, srv CriticalServiceServer) {
	// If the following call pancis, it indicates UnimplementedCriticalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CriticalService_ServiceDesc, srv)
}

func _CriticalService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CriticalServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CriticalService_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CriticalServiceServer).Connect(ctx, req.(*ConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CriticalService_UpdateNodeCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionAmount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CriticalServiceServer).UpdateNodeCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CriticalService_UpdateNodeCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CriticalServiceServer).UpdateNodeCount(ctx, req.(*ConnectionAmount))
	}
	return interceptor(ctx, in, info, handler)
}

func _CriticalService_RequestAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CriticalServiceServer).RequestAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CriticalService_RequestAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CriticalServiceServer).RequestAccess(ctx, req.(*AccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CriticalService_ServiceDesc is the grpc.ServiceDesc for CriticalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CriticalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CriticalService",
	HandlerType: (*CriticalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _CriticalService_Connect_Handler,
		},
		{
			MethodName: "UpdateNodeCount",
			Handler:    _CriticalService_UpdateNodeCount_Handler,
		},
		{
			MethodName: "RequestAccess",
			Handler:    _CriticalService_RequestAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}
